# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://gauravadlakha1509.github.io/power_school_demo/"

git_url = "https://github.com/gauravadlakha1509/power_school_demo/tree/master/"

def custom_doc_links(name): return None
